spring.application.name=${SPRING_APPLICATION_NAME}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

hunter.api.key=${HUNTER_API_KEY}

app.email.username=${APP_EMAIL_USERNAME}
app.email.password=${APP_EMAIL_PASSWORD}
app.email.to=${APP_EMAIL_TO}

github.token=${GITHUB_TOKEN}
github.username=${GITHUB_USERNAME}